version: '3'

services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"

  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin